# Deployment: Defines the desired state for our application pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-ui-frontend
  template:
    metadata:
      labels:
        app: chat-ui-frontend
    spec:
      containers:
        - name: chat-ui-frontend
          image: IMAGE_PLACEHOLDER # This will be replaced by Cloud Build
          ports:
            - containerPort: 80
